export const hindi: Record<string, string> = {
  view: "देखें",
  create: "बनाएँ",
  edit: "संपादित करें",
  delete: "हटाएँ",
  submit: "जमा करें",
  review: "समीक्षा",
  approve: "स्वीकार करें",
  export: "निर्यात",
  manage: "प्रबंधन",
  contact: "संपर्क",
  employment: "रोजगार",
  salary: "वेतन",
  bank: "बैंक",
  identity: "पहचान",
  confidential: "गोपनीय",
  own: "अपने रिकॉर्ड",
  team: "नियुक्त टीम",
  site: "चयनित साइट",
  organization: "संगठन रिपोर्ट",
  super_admin: "सुपर एडमिन",
  admin: "एडमिन",
  hr: "एचआर",
  jr_hr: "जूनियर एचआर",
  employee: "कर्मचारी",
  manager: "प्रबंधक",
  supervisor: "पर्यवेक्षक",
  "Self service": "स्वयं सेवा",
  People: "कर्मचारी",
  Administration: "प्रशासन",
  Operations: "संचालन",
  Finance: "वित्त",
  Communication: "संचार",
  Insights: "विश्लेषण",
  pending: "लंबित",
  approved: "स्वीकृत",
  rejected: "अस्वीकृत",
  draft: "ड्राफ्ट",
};
